#!/usr/bin/env bash
# on-subagent-delegation-start.sh — Pantheon SubagentStart Audit Hook
# Logs when Zeus delegates to a subagent.
#
# Honest telemetry (Council P1-1, 2026-08-06; P0-2, 2026-08-06 2nd session):
# the previous version read AGENT_NAME from env (always '' — opencode
# tool.execute hooks carry no agent_id) and TASK_DESC from payload.tool_name
# (always 'task' — useless). This version reads the Claude Code protocol
# payload {tool_name, tool_input, agent_id, session_id, delegation_id} from
# stdin and derives:
#     agent = tool_input.subagent_type (task tool) -> payload agent_id (the
#             plugin's BEFORE-time agent — never after-time result junk) ->
#             tool_name -> env AGENT_NAME -> 'unknown'. Never 'unknown' when
#             subagent_type is present.
#     task  = tool_input.description (the real delegation task) -> env
#             TASK_DESC -> $1 -> tool name. Falls back to the tool name when
#             no description is supplied.
#     delegation_id = payload.delegation_id — generated by the plugin in
#             tool.execute.before (crypto.randomUUID, P0-2). The stop hook
#             receives the SAME id (via the callID-keyed before-record) so
#             delegations.log joins SubagentStart <-> SubagentStop on it.
# All fields pass through a primitive sanitizer — a merged result blob can
# never contaminate agent/session_id/delegation_id.
set -euo pipefail

# Project-local by default; set XDG_STATE_HOME for system-wide logging
if [ -n "${LOG_DIR:-}" ]; then
    LOG_DIR="$LOG_DIR"
elif [ -n "${XDG_STATE_HOME:-}" ]; then
    LOG_DIR="$XDG_STATE_HOME/pantheon/hooks"
else
    LOG_DIR="logs/agent-sessions"
fi
mkdir -p "$LOG_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Preserve the pre-derivation env values (derived fields overwrite them below).
ENV_AGENT_NAME="${AGENT_NAME:-}"
ENV_TASK_DESC="${TASK_DESC:-}"
ARG_TASK_DESC="${1:-}"

# The Claude Code protocol payload arrives on stdin (hook-runner always pipes
# it, even empty). Buffer it in a temp file — prompts can exceed argv limits.
TMP_IN=$(mktemp "${TMPDIR:-/tmp}/subagent-start.XXXXXX")
TMP_PY=$(mktemp "${TMPDIR:-/tmp}/subagent-start.XXXXXX.py")
trap 'rm -f "$TMP_IN" "$TMP_PY"' EXIT
cat > "$TMP_IN"

# Derivation logic: agent + task + session_id + delegation_id from the
# payload. (Kept in a temp file — heredocs inside $(...) are not portable.)
cat > "$TMP_PY" <<'PY'
import sys
import json

def prim(v):
    """P0-1 sanitizer: primitives -> str; junk (dicts/lists from a merged
    result blob) -> '' so log fields are never contaminated."""
    if isinstance(v, str):
        return v
    if isinstance(v, (int, float, bool)):
        return str(v)
    return ''

try:
    with open(sys.argv[1], encoding='utf-8') as f:
        payload = json.load(f)
except Exception:
    payload = {}

env_agent = sys.argv[2] if len(sys.argv) > 2 else ''
tool_name = payload.get('tool_name') or ''
ti = payload.get('tool_input')
if not isinstance(ti, dict):
    ti = {}
session_id = prim(payload.get('session_id'))
delegation_id = prim(payload.get('delegation_id'))

# Agent (P0-2): subagent_type -> env AGENT_NAME (plugin agent_id from the
# before-time record) -> tool_name -> 'unknown'
agent = ti.get('subagent_type') or ti.get('subagentType') or env_agent or tool_name or ''
# Task: description (real delegation task) -> env TASK_DESC -> $1 -> agent
task = ti.get('description') or ''
if isinstance(task, str):
    task = task.strip()

print('%s\t%s\t%s\t%s' % (prim(agent), prim(task), session_id, delegation_id))
PY

DERIVED=$(python3 "$TMP_PY" "$TMP_IN" "$ENV_AGENT_NAME" 2>/dev/null || printf 'unknown\t\t\t')

# cut is positional (read collapses consecutive tabs on empty fields).
AGENT_NAME=$(printf '%s' "$DERIVED" | cut -f1)
TASK_DESC=$(printf '%s' "$DERIVED" | cut -f2)
SESSION_ID=$(printf '%s' "$DERIVED" | cut -f3)
DELEGATION_ID=$(printf '%s' "$DERIVED" | cut -f4)

# Agent fallback chain (subagent_type -> env -> tool_name -> 'unknown').
if [ -z "$AGENT_NAME" ]; then
    AGENT_NAME="$ENV_AGENT_NAME"
fi
if [ -z "$AGENT_NAME" ]; then
    AGENT_NAME="unknown"
fi

# Task fallback (stdin description -> env TASK_DESC -> $1 -> tool name).
if [ -z "$TASK_DESC" ]; then
    TASK_DESC="${ENV_TASK_DESC:-$ARG_TASK_DESC}"
fi
if [ -z "$TASK_DESC" ]; then
    TASK_DESC="$AGENT_NAME"
fi

# Emit a schema-compatible line: {event, timestamp, agent, task, session_id,
# delegation_id} — P0-2: delegation_id is the join key with SubagentStop.
# Built with json.dumps so arbitrary description text cannot break the JSON.
LOG_LINE=$(python3 -c '
import json
import sys
print(json.dumps({
    "event": "SubagentStart",
    "timestamp": sys.argv[1],
    "agent": sys.argv[2],
    "task": sys.argv[3],
    "session_id": sys.argv[4],
    "delegation_id": sys.argv[5],
}, ensure_ascii=False))
' "$TIMESTAMP" "$AGENT_NAME" "$TASK_DESC" "$SESSION_ID" "$DELEGATION_ID")

echo "$LOG_LINE" >> "$LOG_DIR/delegations.log"

echo "[DELEGATION] $AGENT_NAME started → $LOG_DIR/delegations.log" >&2

# --- Dispatch-time validation: check target against routing.yml ---
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/../.." && pwd)"
ROUTING_FILE="$REPO_ROOT/routing.yml"
if [ -f "$ROUTING_FILE" ] && [ -n "$AGENT_NAME" ] && [ "$AGENT_NAME" != "unknown" ]; then
    ESCAPED_AGENT_NAME=$(printf '%s\n' "$AGENT_NAME" | sed 's/[][(){}.^$*+?|\/\\-]/\\&/g')
    if grep -qE "^[[:space:]]*-[[:space:]]+target:[[:space:]]+$ESCAPED_AGENT_NAME[[:space:]]*$" "$ROUTING_FILE" 2>/dev/null; then
        echo "[VALIDATION] ✅ Target '$AGENT_NAME' found in routing.yml" >&2
    else
        echo "[VALIDATION] ⚠️ Target '$AGENT_NAME' NOT in routing.yml delegation rules" >&2
    fi
elif [ -f "$ROUTING_FILE" ]; then
    echo "[VALIDATION] ⚠️ Could not identify the delegated agent (agent='$AGENT_NAME') — skipping routing.yml validation" >&2
elif [ ! -f "$ROUTING_FILE" ]; then
    echo "[VALIDATION] ⚠️ Could not read routing.yml for validation" >&2
fi

# --- Cost estimation for delegation ---
declare -A TIER_MAP
TIER_MAP[athena]="premium"
TIER_MAP[themis]="premium"
TIER_MAP[hermes]="default"
TIER_MAP[aphrodite]="default"
TIER_MAP[demeter]="default"
TIER_MAP[prometheus]="default"
TIER_MAP[hephaestus]="default"
TIER_MAP[gaia]="default"
TIER_MAP[zeus]="default"
TIER_MAP[apollo]="fast"
TIER_MAP[nyx]="fast"
TIER_MAP[iris]="fast"
TIER_MAP[mnemosyne]="fast"
TIER_MAP[talos]="fast"

TIER="${TIER_MAP[$AGENT_NAME]:-default}"

case "$TIER" in
    premium)
        COST_MIN=0.50
        COST_MAX=2.00
        COST_EST=1.25
        ;;
    fast)
        COST_MIN=0.02
        COST_MAX=0.10
        COST_EST=0.06
        ;;
    *)
        COST_MIN=0.10
        COST_MAX=0.50
        COST_EST=0.30
        ;;
esac

# Format cost with 2 decimal places
COST_EST_FMT=$(printf "%.2f" "$COST_EST")

if [ "$TIER" = "premium" ]; then
    echo "[COST_WARN] High-cost delegation to $AGENT_NAME — estimated \$$COST_EST_FMT" >&2
fi

if (( $(echo "$COST_EST > 5.00" | bc -l 2>/dev/null) )); then
    echo "[COST_ALERT] Expensive delegation to $AGENT_NAME — consider if subtask is possible" >&2
fi

echo "[COST] Delegation to $AGENT_NAME — tier: $TIER — estimated: \$$COST_EST_FMT" >&2

exit 0
